version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laracast-app
    volumes:
      -  ./code:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: laracast-mysql
    restart: unless-stopped
    tty: true
    ports:
      -  "4306:3306"
    volumes:
      - ./config/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laracast_sandbox
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: laracast-nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge